### ISSUE TITLE
Any thoughts on supporting PATCH?

### ISSUE THREAD

**Issue by yrashk** [awetzel/ewebmachine#13]
http://restcookbook.com/HTTP%20Methods/patch/

**Comment by awetzel** [comment]
Actually the issue with PATCH is it is somewhat redondant with "PUT" or "POST as process", since : 

- sometimes it is used in an idempotent way, in this case it is better to use PUT. To make the put patching more explicit (instead of adding specific resources allowing only put representing patches), you can specify the patch as a specific representation of your resource. And use it to differentiate the parsing and action. 

```http
PUT /my/resource
Content-Type: application/json; only_part=user

{"username": "joe"}
```

```elixir
content-types-accepted: [{{"application/json",%{"only_part"=>"user"}},:patch_user_json}, {"application/json",:from_full_json}}

defh patch_user_json do
  # parse and patch 
end
```

- it has side effects and is not idempotent, but does not create resource. So it is exactly like a `POST` as process (`post_is_create == false`). The only constraint added is that it should never create resource, but actually this contraint does not ensure anything really useful : 
  - because if some resource is created, a POST as `post_is_create == true` is what you are looking for.
  - the constraint : "has side effects, but in them no resource creation" has no implication and no use for caching or anything else, which is the point of HTTP.

Finally, use of `PATCH` is more something to add a semantic function to your resource with no useful functional addition (actually as "DELETE" :) ... ). 
So if you have to use it, you can do : 

- add "PATCH" to [known_methods](http://hexdocs.pm/ewebmachine/Ewebmachine.Handlers.html#known_methods/2), then is your resource_exists implementation, change tell webmachine if it is "PATCH" as a "PUT" or "PATH" as a "POST"

```elixir
known_methods do:
  ["GET", "HEAD", "POST", "PUT", "DELETE", "PATCH","TRACE", "CONNECT", "OPTIONS"]
allowed_methods do: ["GET","PATCH"]
defh resource_exists(%{method: "PATCH"}=conn,state), do:
  {true,%{conn| method: "POST"},state}
```

Also, ewebmachine follows the http decision tree as designed initially by Alan Dean. It implements the third version which is the one currently implemented by basho/webmachine. So if we want to improve the core decisions of ewebmachine, I would prefer to work on https://github.com/for-GET/http-decision-diagram which prepare a V4 of the diagram. Then implement the entire specification into `Ewebmachine.Core.v4`. Currently they think that their current implementation is PATCH friendly : 

https://github.com/for-GET/http-decision-diagram/issues/35

For the moment, the only support I can add is just add "PATCH" to the default `known_methods`

**Comment by awetzel** [comment]
I added the PATCH method to the known method. Not sure where to put some doc about how to use it. Maybe an "examples" directory or a "ewebmachine_examples" repository are good ideas.
